export declare const ext: (types: string) => RegExp;
declare const _default: {
    required: RegExp;
    english: RegExp;
    alphanum: RegExp;
    chinese: RegExp;
    nospace: RegExp;
    float: RegExp;
    positivefloat: RegExp;
    integer: RegExp;
    positiveint: RegExp;
    decimal: RegExp;
    percent: RegExp;
    email: RegExp;
    http: RegExp;
    phone: RegExp;
    year: RegExp;
    month: RegExp;
    day: RegExp;
    hour: RegExp;
    minute: RegExp;
    hmt: RegExp;
    time: RegExp;
    date: RegExp;
    datetime: RegExp;
    path: RegExp;
    file: RegExp;
    imgurl: RegExp;
};
export default _default;
//# sourceMappingURL=rules.d.ts.map